# Local Gitlab-CI file for SDP Logging

# ============================================================================
# Build python packages
# ============================================================================

build:ska-sdp-logging_dev: # Executed on a commit
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/logging

build:ska-sdp-logging:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/logging

# ============================================================================
# Testing built python package
# ============================================================================

test:ska-sdp-logging:
  extends: .tango_tests
  stage: test
  script:
    - coverage --version
    - cd src/logging
    - python3 setup.py test
    # Make the coverage report available at the top level, which will merge it.
    - mv .coverage ../../$CI_JOB_NAME.coverage
  artifacts:
    paths:
      - ./$CI_JOB_NAME.coverage
    expire_in: 1 week
    when: always

## ============================================================================
## Publish python packages
## ============================================================================

publish:ska-sdp-logging-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-logging_dev
  variables:
    BUILD_PATH: src/logging

publish:ska-sdp-logging:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-logging
  variables:
    BUILD_PATH: src/logging
