# Local Gitlab-CI file for SDP Logging

# ============================================================================
# Build python packages
# ============================================================================

build:ska-sdp-logging_dev: # Executed on a commit
  extends: .build_python_dev
  variables:
    BUILD_PATH: src/logging

build:ska-sdp-logging:
  extends: .build_python_release
  variables:
    BUILD_PATH: src/logging

# ============================================================================
# Testing built python package
# ============================================================================

test:ska-sdp-logging:
  extends: .tango_tests
  stage: test
  script:
    - cd src/logging
    - mkdir -p build/reports
    - python3 setup.py test
    - mv htmlcov build/sdp_logging_htmlcov
    - mv coverage.xml build/code-coverage.xml
    - mv build ../../build
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

## ============================================================================
## Publish python packages
## ============================================================================

publish:ska-sdp-logging-dev:
  extends: .publish_python_dev
  dependencies:
    - build:ska-sdp-logging_dev
  variables:
    BUILD_PATH: src/logging

publish:ska-sdp-logging:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-logging
  variables:
    BUILD_PATH: src/logging
