# GitLab CI jobs for SDP logging library

.env: &env
  variables:
    BUILD_PATH: src/logging

# ============================================================================
# Build Python package
# ============================================================================

# Executed on a non-master commit
build:ska-sdp-logging_dev:
  extends: .build_python_dev
  <<: *env

# Executed on a master commit
build:ska-sdp-logging:
  extends: .build_python_release
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================

test:ska-sdp-logging:
  extends:
    - .test_python
    - .test_with_coverage
  <<: *env

# ============================================================================
# Publish Python package (master only)
# ============================================================================

publish:ska-sdp-logging:
  extends: .publish_python_release
  dependencies:
    - build:ska-sdp-logging
  <<: *env
